adobe/S3Mock

README.md

Adds build status badge from Travis-CI build
---
@agudian: Please review, merge and delete branch

adds TravisCI Build Badge

---

README.md

Add "Latest Release" badge to readme

---

README.md

README.md - typo fix

---

AUTHORS
src/main/java/com/adobe/testing/s3mock/domain/FileStore.java
src/test/java/com/adobe/testing/s3mock/domain/FileStoreTest.java

Adds https://github.com/mattelacchiato as an Author + cleans up code
---
@agudian: Please review, merge and delete branch.

adds https://github.com/mattelacchiato to list of authors

---

AUTHORS
pom.xml
src/main/java/com/adobe/testing/s3mock/FileStoreController.java
src/main/java/com/adobe/testing/s3mock/domain/FileStore.java
src/main/java/com/adobe/testing/s3mock/domain/MultipartUploadInfo.java
src/main/java/com/adobe/testing/s3mock/domain/S3Object.java
src/main/java/com/adobe/testing/s3mock/dto/CompleteMultipartUploadResult.java
src/main/java/com/adobe/testing/s3mock/dto/ListAllMyBucketsResult.java
src/main/java/com/adobe/testing/s3mock/dto/ListMultipartUploadsResult.java
src/main/java/com/adobe/testing/s3mock/dto/ListPartsResult.java
src/main/java/com/adobe/testing/s3mock/dto/MultipartUpload.java
src/main/java/com/adobe/testing/s3mock/dto/ObjectRef.java
src/main/resources/application.properties
src/test/java/com/adobe/testing/s3mock/domain/FileStoreTest.java
src/test/java/com/adobe/testing/s3mock/domain/ObjectRefTest.java
src/test/java/com/adobe/testing/s3mock/its/AmazonClientUploadIT.java

Adds `final` modifiers, removes empty lines and extends the list of autors.
---
@agudian: Please review, merge and delete branch.

cleans up code and adds Martin Grotzke to the list of Authors

---

AUTHORS
src/test/java/com/adobe/testing/s3mock/its/AmazonClientUploadIT.java

@timoe Please review and rebase+merge.

Add Artem to list of contributors and allow for a minute clock skew in the IT to make the tests more stable

---

.travis.yml
.travis/release.sh
.travis/settings.xml
.travis/travis-release.sh
pom.xml

@timoe please review and rebase+merge.

#1 Add scripts for releasing from Travis.

---

AUTHORS
src/main/java/com/adobe/testing/s3mock/S3MockApplication.java
src/main/java/com/adobe/testing/s3mock/S3MockRule.java
src/test/java/com/adobe/testing/s3mock/its/AmazonClientUploadIT.java

@agudian: Please review, merge + rebase

extend list of authors and cleans up code

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md
COPYRIGHT
README.md

@timoe please review / merge / delete branch.

Add CONTRIBUTING.md with link to CLA and add some simple PR / issue templates.

---

AUTHORS
src/main/java/com/adobe/testing/s3mock/FileStoreController.java
src/main/java/com/adobe/testing/s3mock/S3MockApplication.java
src/main/java/com/adobe/testing/s3mock/domain/FileStore.java
src/main/java/com/adobe/testing/s3mock/domain/MultipartUploadInfo.java
src/main/java/com/adobe/testing/s3mock/dto/CopyPartResult.java
src/test/java/com/adobe/testing/s3mock/dto/CopyPartResultTest.java
src/test/java/com/adobe/testing/s3mock/its/AmazonClientUploadIT.java

Along with it I cleaned up code.
---
@agudian: Please review, rebase + merge and delete branch

adds Thomas Beckmann to list of authors

---

README.md
testsupport/pom.xml
testsupport/testng/pom.xml
testsupport/testng/src/main/java/com/adobe/testing/s3mock/testng/S3Mock.java
testsupport/testng/src/main/java/com/adobe/testing/s3mock/testng/S3MockListener.java
testsupport/testng/src/test/java/com/adobe/testing/s3mock/testng/S3MockListenerXMLConfigurationTest.java
testsupport/testng/src/test/resources/sampleFile.txt
testsupport/testng/src/test/resources/testng.xml

@agudian Adding TestNG variant

Adding testng variant, supporting through IExecutionListener

---

README.md
pom.xml
server/pom.xml
server/src/main/java/com/adobe/testing/s3mock/S3MockApplication.java

The previously described way to locally run the app using the Maven command didn't work anymore after the module refactoring.

Fix local startup and adjust documentation on that.

---

server/pom.xml
server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
server/src/test/java/com/adobe/testing/s3mock/its/ErrorResponsesIT.java
server/src/test/java/com/adobe/testing/s3mock/its/PlainHttpIT.java
server/src/test/java/com/adobe/testing/s3mock/its/S3TestBase.java
testsupport/common/src/main/java/com/adobe/testing/s3mock/testsupport/common/S3MockStarter.java

* `DELETE` non existing Objects will return 204 anyway
* `PUT` Object returns 200 instead of 204
https://github.com/adobe/S3Mock/issues/47
https://github.com/adobe/S3Mock/issues/50
---
@agudian: Please review, rebase+merge and delete branch.

Adapt status codes 

---

pom.xml
testsupport/junit5/pom.xml

Update to JUnit 5.2.0 and use the related surefire-provider version that is compatible with the latest Surefire version.
@timoe please review / merge

Update JUnit 5 to latest version

---

server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
server/src/main/java/com/adobe/testing/s3mock/domain/FileStore.java
server/src/main/java/com/adobe/testing/s3mock/domain/Tag.java
server/src/main/java/com/adobe/testing/s3mock/dto/Tagging.java
server/src/test/java/com/adobe/testing/s3mock/domain/FileStoreTest.java
server/src/test/java/com/adobe/testing/s3mock/its/AmazonClientUploadIT.java
testsupport/testng/src/test/resources/testng.xml

cleans up code, sets final, removes unused variables etc.
---
@agudian: Please review, rebase + merge.

cleans up code

---

server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
server/src/test/java/com/adobe/testing/s3mock/its/AmazonClientUploadIT.java

When calling getObject there are 2 hedder parameters that can be set
to test whether the e-tag exists and should or should not match.

respect --if-match and --if-none-match at getObject()

---

AUTHORS
server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
server/src/test/java/com/adobe/testing/s3mock/its/AmazonClientUploadIT.java
server/src/test/java/com/adobe/testing/s3mock/its/PlainHttpIT.java

adds Lasse Reedtz to the list of authors and cleaned up code a bit

---

AUTHORS
server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
server/src/main/java/com/adobe/testing/s3mock/S3MockApplication.java
server/src/test/java/com/adobe/testing/s3mock/domain/FileStoreTest.java
server/src/test/java/com/adobe/testing/s3mock/domain/ObjectRefTest.java
server/src/test/java/com/adobe/testing/s3mock/its/AmazonClientUploadIT.java
server/src/test/java/com/adobe/testing/s3mock/its/ErrorResponsesIT.java
server/src/test/java/com/adobe/testing/s3mock/its/S3TestBase.java
testsupport/junit4/src/test/java/com/adobe/testing/s3mock/junit4/S3MockRuleTest.java

I'd like to have ListObjectsV2 as one separat commit so I squashed these 6 commits. I also went through the code and removed some of IDEAs Inspections warning and added @sveryovka to the list of authors.

adds sveryovka as an author, squashed last 6 commits and polished code a bit

---

pom.xml
testsupport/junit5/pom.xml

* Update JRE to latest available JRE for Alpine (8u171)
* Update to latest SpringBoot 2.0.3
* Update to Surefire/Failsafe 2.22.0 and remove the now obsolete config bits for JUnit5, as it's now all working out of the box.

Update JRE version and SpringBoot, update Surefire version.

---

server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
server/src/test/java/com/adobe/testing/s3mock/its/AmazonClientUploadIT.java
server/src/test/java/com/adobe/testing/s3mock/its/ErrorResponsesIT.java

The commit also contains some auto-cleanups like adding finals and so on, so please don't merge before #90 in case you come across that one to avoid more conflicts there.
Fixes #92

Fix batch-delete behaviour for non-existing files

---

AUTHORS

Adds https://github.com/ptomala5 as an author

adds Ptomala5 as an author

---

server/pom.xml
server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
server/src/main/java/com/adobe/testing/s3mock/domain/FileStore.java
server/src/test/java/com/adobe/testing/s3mock/domain/FileStoreTest.java
server/src/test/java/com/adobe/testing/s3mock/its/AmazonClientUploadIT.java
server/src/test/java/com/adobe/testing/s3mock/util/EtagInputStream.java

Implementation of special etag calculation.
See https://stackoverflow.com/questions/12186993/what-is-the-algorithm-to-compute-the-amazon-s3-etag-for-a-file-larger-than-5gb
#66

Multipart md5 hash calculation is incorrect #66

---

pom.xml

Update JDK, Alpine, Spring and JUnit 5

---

pom.xml

updates spring boot to 2.1.5.RELEASE

updates spring boot version

---

pom.xml

AWS SDK 2.7.19

---

README.md

Changed broken links in `README.md`
None
N/A

Fixed broken links on readme

---

README.md

Language and Star Badge Added

---

server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
server/src/main/java/com/adobe/testing/s3mock/KmsValidationFilter.java
server/src/main/java/com/adobe/testing/s3mock/S3MockApplication.java

- Avoided unnecessary boxing of Boolean/Long
- Simplified expressions

Fixed minor code analysis warnings

---

pom.xml

Upgraded Spring Boot to the latest available (2.1.9.RELEASE)
N/A

Upgrade spring-boot to 2.1.9.RELEASE

---

server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
server/src/test/java/com/adobe/testing/s3mock/its/PlainHttpIT.java

When accessing `headObject`, it is attempted to parse the given MIME type. If parsing fails, `InvalidMediaTypeException` is thrown. As `putObject` with a unknown *Content-Type* is accepted, this will try to parse a MIME type unless blank and subsequently throw the exception.
So, similar to AWS S3's behaviour, this change will give a *Content-Type* of *binary/octet-stream* for unknown MIME types.
* Fixes #126 (Bug) 
* Closes #127 (Abandoned PR)

Handle invalid MIME types in headObject

---

README.md

Added Docker pull badge

---

.travis.yml

Travis CI: oraclejdk8 -> openjdk8

---

server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
server/src/test/java/com/adobe/testing/s3mock/its/PlainHttpIT.java

Fixing completeMultipartUpload content-type
https://github.com/adobe/S3Mock/issues/210

Fixing completeMultipartUpload content-type

---

server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
server/src/test/java/com/adobe/testing/s3mock/its/ErrorResponsesIT.java

Checking part-number limits in `putObjectPart`
https://github.com/adobe/S3Mock/issues/221

Checking part-number limits

---

.github/workflows/maven-ci-and-prb.yml

Fix workflow yml

---

.github/workflows/maven-release.yml
.github/workflows/perform-release.sh
.github/workflows/settings.xml
pom.xml

Add GitHub action to perform a manually triggered release

---

build-config/src/main/resources/build-config/checkstyle.xml
pom.xml

Update checkstyle and fix errors in the ruleset as reported by the new version.

---

server/src/main/java/com/adobe/testing/s3mock/domain/FileStore.java
server/src/test/java/com/adobe/testing/s3mock/domain/FileStoreTest.java

It's possible to PUT an object with an absolute path.
Using the same path to GET an object should work too. A path can't be
resolved in the local bucket root if it's absolute.
Also: minor fixes and cleanup
Fixes #245 and #248

Fixes getS3Object with absolute path

---

build-config/src/main/resources/build-config/checkstyle.xml
pom.xml
server/src/main/java/com/adobe/testing/s3mock/FaviconController.java
server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
server/src/main/java/com/adobe/testing/s3mock/S3MockApplication.java
server/src/main/java/com/adobe/testing/s3mock/domain/FileStore.java
server/src/main/java/com/adobe/testing/s3mock/util/MetadataUtil.java
server/src/test/java/com/adobe/testing/s3mock/its/PlainHttpIT.java
server/src/test/java/com/adobe/testing/s3mock/its/S3TestBase.java
testsupport/common/pom.xml
testsupport/junit4/pom.xml
testsupport/junit5/pom.xml
testsupport/pom.xml
testsupport/testng/pom.xml

Decided to scrub through the POMs and unit tests, simplify, refactor and clean up classes and POM files.

Refactings, cleanup and updates

---

.github/workflows/create-release-from-tag.yml

I may have broken the action by triggering it on every push on
branch "main" - tags are not pushed to branches, D'oh!
Fixup for #265
N/A

Fix release creation trigger

---

integration-tests/src/test/java/com/adobe/testing/s3mock/its/AmazonClientUploadIT.java
integration-tests/src/test/java/com/adobe/testing/s3mock/its/EtagInputStream.java
pom.xml

Manage plugin versions in properties, sort alphabetically.
Update various plugin versions to newest releases.
N/A

Maven plugin management and updates

---

CHANGELOG.md
README.md
build-config/pom.xml
docker/pom.xml
docker/src/main/docker/Dockerfile
integration-tests/pom.xml
pom.xml
server/pom.xml
server/src/main/java/com/adobe/testing/s3mock/domain/FileStore.java
testsupport/common/pom.xml
testsupport/junit4/pom.xml
testsupport/junit5/pom.xml
testsupport/pom.xml
testsupport/testcontainers/pom.xml
testsupport/testcontainers/src/main/java/com/adobe/testing/s3mock/testcontainers/S3MockContainer.java
testsupport/testcontainers/src/test/java/com/adobe/testing/s3mock/testcontainers/S3MockContainerJupiterTest.java
testsupport/testcontainers/src/test/java/com/adobe/testing/s3mock/testcontainers/S3MockContainerManualTest.java
testsupport/testcontainers/src/test/java/com/adobe/testing/s3mock/testcontainers/S3MockContainerTestBase.java
testsupport/testcontainers/src/test/resources/sampleFile.txt
testsupport/testng/pom.xml

Adds a module to make using S3Mock easy with [Testcontainers](https://www.testcontainers.org/).
N/A

Add Testcontainers support

---

.github/workflows/maven-ci-and-prb.yml
.github/workflows/maven-release.yml

use GitHub Actions setup-java v2

use setup-java v2

---

CHANGELOG.md
README.md
server/src/main/java/com/adobe/testing/s3mock/domain/FileStore.java
server/src/test/java/com/adobe/testing/s3mock/domain/FileStoreTest.java

Default is "false", all files are removed.
Fixes #286

Add option "retainFilesOnExit" to keep created files

---

docker/Dockerfile

Use Java 17
Build JRE from actual dependencies

Docker optimizations

---

testsupport/pom.xml

Skip Testcontainers build if -DskipDocker is used

---

integration-tests/src/test/java/com/adobe/testing/s3mock/its/ListObjectIT.java
server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
server/src/test/java/com/adobe/testing/s3mock/FileStoreControllerTest.java

Fixes empty delimiter in list APIs
Fixes #306

Fixes empty delimiter in list APIs

---

integration-tests/src/test/java/com/adobe/testing/s3mock/its/MultiPartUploadIT.java
server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
server/src/main/java/com/adobe/testing/s3mock/domain/FileStore.java
server/src/main/java/com/adobe/testing/s3mock/util/AwsHttpParameters.java
server/src/test/java/com/adobe/testing/s3mock/domain/FileStoreTest.java

Copy range is optional for uploadCopyPart API.

---

integration-tests/src/test/java/com/adobe/testing/s3mock/its/MultiPartUploadIT.java

Listing parts with uploadId correctly returns empty list if multipart
upload was completed or aborted.
Fixes, or rather tests #217

Test listing parts after abort or complete

---

integration-tests/src/test/java/com/adobe/testing/s3mock/its/AmazonClientUploadIT.java
integration-tests/src/test/java/com/adobe/testing/s3mock/its/MultiPartUploadIT.java
server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java

Verify source key exists on CopyObject and CopyObjectPart

---

integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/MultiPartUploadIT.kt
server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java

ListParts returns 404 on unknown upload id.

---

integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/AmazonClientUploadIT.kt
server/src/main/java/com/adobe/testing/s3mock/store/FileStore.java

First fix was implemented with #468
Turns out this was not working consistently.
Also add more integration tests.
#569
#468

Fix handling of userMetadata in CopyObject REPLACE and COPY cases

---

build-config/pom.xml
docker/pom.xml
integration-tests/pom.xml
pom.xml
server/pom.xml
testsupport/common/pom.xml
testsupport/junit4/pom.xml
testsupport/junit5/pom.xml
testsupport/pom.xml
testsupport/testcontainers/pom.xml
testsupport/testng/pom.xml

Lots of wrong indents and wrongly sorted elements in our POMs.
To run manually, execute
"mvn com.github.ekryd.sortpom:sortpom-maven-plugin:sort"
N/A

Add sortpom-maven-plugin, run sortpom

---

CHANGELOG.md
server/pom.xml

This helps applications start up faster.
Fixes #751

Add Spring Component Indexes

---

integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/AmazonClientUploadV1IT.kt
integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/BucketTestsV1IT.kt
integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/BucketTestsV2IT.kt
integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ConcurrencyIT.kt
integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/CopyObjectV1IT.kt
integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ErrorResponsesV1IT.kt
integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ErrorResponsesV2IT.kt
integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/GetPutDeleteObjectV1IT.kt
integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/LegalHoldV2IT.kt
integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ListObjectV1IT.kt
integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ListObjectV1MaxKeysIT.kt
integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ListObjectV1PaginationIT.kt
integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/MultiPartUploadV1IT.kt
integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/MultiPartUploadV2IT.kt
integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ObjectTaggingV1IT.kt
integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ObjectTaggingV2IT.kt
integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/PlainHttpIT.kt
integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/RetentionV2IT.kt
integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/S3TestBase.kt

* Various IntegrationTest refactorings
N/A

Various IntegrationTest refactorings

---

server/src/main/java/com/adobe/testing/s3mock/store/StoreConfiguration.java

This change uses the atomic and thus thread-safe `Files.createTempDirectory` implementation to create the root directory if none is provided.
#837 
Testing for this race condition (or its absence) programmatically w/o including special hooks in the code is somewhat tricky, which is why I haven't written any test for it so far...

Avoid root folder temporary directory race condition (closes #837)

---

CHANGELOG.md
README.md
build-config/pom.xml
docker/pom.xml
integration-tests/pom.xml
integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/BucketV2IT.kt
pom.xml
server/pom.xml
server/src/main/java/com/adobe/testing/s3mock/BucketController.java
server/src/main/java/com/adobe/testing/s3mock/S3MockConfiguration.java
server/src/main/java/com/adobe/testing/s3mock/S3MockProperties.java
server/src/main/java/com/adobe/testing/s3mock/dto/LocationConstraint.java
server/src/main/java/com/adobe/testing/s3mock/dto/RegionSerializer.java
server/src/main/java/com/adobe/testing/s3mock/util/AwsHttpParameters.java
server/src/main/resources/application.properties
server/src/test/java/com/adobe/testing/s3mock/dto/LocationConstraintTest.java
server/src/test/resources/com/adobe/testing/s3mock/dto/LocationConstraintTest_testSerialization.xml
testsupport/common/pom.xml
testsupport/junit4/pom.xml
testsupport/junit5/pom.xml
testsupport/pom.xml
testsupport/testcontainers/pom.xml
testsupport/testng/pom.xml

* Support for GetBucketLocation API (fixes #985)
Fixes #985

Add GetBucketLocation API

---

server/src/main/java/com/adobe/testing/s3mock/util/AwsChunkedDecodingInputStream.java

Speed up AwsChunkedDecodingInputStream
Fixes #1115

Speed up AwsChunkedDecodingInputStream

---

integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ListObjectV2IT.kt
server/src/main/java/com/adobe/testing/s3mock/dto/S3Object.java
server/src/main/java/com/adobe/testing/s3mock/service/BucketService.java
server/src/test/java/com/adobe/testing/s3mock/BucketControllerTest.java
server/src/test/java/com/adobe/testing/s3mock/dto/ListBucketResultTest.java
server/src/test/java/com/adobe/testing/s3mock/dto/ListBucketResultV2Test.java
server/src/test/java/com/adobe/testing/s3mock/service/ServiceTestBase.java
server/src/test/resources/com/adobe/testing/s3mock/dto/ListBucketResultTest_testSerialization.xml
server/src/test/resources/com/adobe/testing/s3mock/dto/ListBucketResultV2Test_testSerialization.xml

Return checksumAlgorithm in ListObjects / ListObjectsV2

---

.github/workflows/codeql.yml
.github/workflows/maven-ci-and-prb.yml
.github/workflows/maven-release.yml

Update build to Java 21

---

CHANGELOG.md
build-config/pom.xml
docker/pom.xml
integration-tests/pom.xml
pom.xml
server/pom.xml
testsupport/common/pom.xml
testsupport/junit4/pom.xml
testsupport/junit5/pom.xml
testsupport/pom.xml
testsupport/testcontainers/pom.xml
testsupport/testng/pom.xml

Accidentally released 3.3.1, meant to release 3.4.0 as features were added and minor dependency versions were updated...

Prepare release of 3.4.0

---

CHANGELOG.md
integration-tests/pom.xml
integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/MultiPartUploadV2IT.kt
integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/S3TestBase.kt
pom.xml

* Test uploads using TransferManager
#1662

Test uploads using TransferManager

---

CHANGELOG.md
build-config/pom.xml
docker/pom.xml
integration-tests/pom.xml
integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/AclIT.kt
integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/MultiPartUploadV2IT.kt
pom.xml
server/pom.xml
server/src/main/java/com/adobe/testing/s3mock/ObjectCannedAclHeaderConverter.java
server/src/main/java/com/adobe/testing/s3mock/ObjectController.java
server/src/main/java/com/adobe/testing/s3mock/S3MockConfiguration.java
server/src/main/java/com/adobe/testing/s3mock/dto/Grantee.java
server/src/main/java/com/adobe/testing/s3mock/dto/Owner.java
server/src/main/java/com/adobe/testing/s3mock/util/AwsHttpHeaders.java
server/src/main/java/com/adobe/testing/s3mock/util/CannedAclUtil.java
testsupport/common/pom.xml
testsupport/junit4/pom.xml
testsupport/junit5/pom.xml
testsupport/pom.xml
testsupport/testcontainers/pom.xml
testsupport/testng/pom.xml

Support canned ACLs

---

integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/GetPutDeleteObjectV1IT.kt

Usage of `HttpsURLConnection` and other classes is unnecessary, we're using the default Apache `HttpClient` everywhere else.
Fixes #1678

Use default Apache client in ITs

---

CHANGELOG.md
README.md

Describe how to use `root` property with Docker.
Fixes #1728

Describe how to use `root` property with Docker.

---

pom.xml

Bump spring-boot.version from 3.3.2 to 3.3.3

---

CHANGELOG.md
build-config/pom.xml
docker/pom.xml
integration-tests/pom.xml
pom.xml
server/pom.xml
testsupport/common/pom.xml
testsupport/junit4/pom.xml
testsupport/junit5/pom.xml
testsupport/pom.xml
testsupport/testcontainers/pom.xml
testsupport/testng/pom.xml

Prepare for 3.11.0

---

.github/workflows/dependency-review.yml
.mvn/jvm.config
CHANGELOG.md
build-config/pom.xml
docker/pom.xml
integration-tests/pom.xml
pom.xml
server/pom.xml
testsupport/common/pom.xml
testsupport/junit4/pom.xml
testsupport/junit5/pom.xml
testsupport/pom.xml
testsupport/testcontainers/pom.xml
testsupport/testng/pom.xml

* Readme changes
* Version bump
* Fix dependency graph
N/A

Prepare for 3.12.0

---

CHANGELOG.md
integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/GetPutDeleteObjectV2IT.kt
server/src/main/java/com/adobe/testing/s3mock/MultipartController.java
server/src/main/java/com/adobe/testing/s3mock/ObjectController.java
server/src/main/java/com/adobe/testing/s3mock/service/ObjectService.java
server/src/test/kotlin/com/adobe/testing/s3mock/service/ObjectServiceTest.kt
server/src/test/kotlin/com/adobe/testing/s3mock/service/ServiceTestBase.kt

Adds If-(Un)modified-Since handling.
Fixes #829

Implement If-(Un)modified-Since

---

CHANGELOG.md
build-config/pom.xml
docker/Dockerfile
docker/pom.xml
integration-tests/pom.xml
integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/CopyObjectV1IT.kt
integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/CopyObjectV2IT.kt
integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/CorsV2IT.kt
integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/GetPutDeleteObjectV1IT.kt
integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/PlainHttpIT.kt
integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/PresignedUrlV2IT.kt
integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/S3TestBase.kt
pom.xml
server/pom.xml
server/src/main/java/com/adobe/testing/s3mock/ObjectController.java
testsupport/common/pom.xml
testsupport/junit4/pom.xml
testsupport/junit5/pom.xml
testsupport/pom.xml
testsupport/testcontainers/pom.xml
testsupport/testng/pom.xml

Prepare 4.0.0

---

integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/PresignedUrlV2IT.kt

Also: Kotlify code
Fixes #2201

Test range requests with presigned url

---

.github/CONTRIBUTING.md
README.md
pom.xml
server/src/main/resources/application-debug.properties
server/src/main/resources/application-trace.properties

Only documentation changes.
N/A

Security and contribution clarifications

---

CHANGELOG.md

Changelog for 4.5.0
