adobe/S3Mock

- pom.xml
This PR upgrades the following dependencies:
* xstream - this also fixes a security vulnerability
* commons-io
* AWS SDK
* Logback
* Commons-codec
* Jodatime
> Upgraded Maven Dependencies

- pom.xml
- src/main/java/com/adobe/testing/s3mock/FileStoreController.java
- src/main/java/com/adobe/testing/s3mock/domain/FileStore.java
- src/main/java/com/adobe/testing/s3mock/dto/ObjectRef.java
- src/test/java/com/adobe/testing/s3mock/its/AmazonClientUploadIT.java
`PUT` operations referring to object keys including path separators (e.g. `folder1/folder2/file`) now extract the object key from given `HttpServletRequest`.
Fixes #8 
---
@agudian: Please review, merge and delete branch.
> Use  object keys containing separators

- src/main/java/com/adobe/testing/s3mock/domain/FileStore.java
- src/test/java/com/adobe/testing/s3mock/domain/FileStoreTest.java
Previously, `getS3Object` was called with a path containing the bucket
path, which will fail, because `getS3Object` expects a path relative to
the bucket.
The path filtering may return folders too, so a folder is not
automatically a stored object.
> Fix getS3Objects for parent directories.

- src/main/java/com/adobe/testing/s3mock/domain/FileStore.java
- src/test/java/com/adobe/testing/s3mock/domain/FileStoreTest.java
Empty prefix should have the same meaning as null prefix.
> Fix getS3Objects for root directory.

- pom.xml
This may already close and release the nexus staging repo automatically, but I'm not sure. We'll have to try it out and maybe add the `nexus-staging:close` goal to the release goals if it's not yet working.
Plus, the configuration properties `nexusUrl` and `serverId` are not specified in the plugin config, although the documentation on https://github.com/sonatype/nexus-maven-plugins/tree/master/staging/maven-plugin describes them as mandatory. It works for deploying to the sonatype-snapshots repository, though. So I'm not sure if they are still required.
@timoe please review / merge / delete the branch.
> Prepare more automated release: use nexus-staging-plugin for deploy phase

- src/main/java/com/adobe/testing/s3mock/FileStoreController.java
- src/main/java/com/adobe/testing/s3mock/S3MockApplication.java
- src/main/java/com/adobe/testing/s3mock/domain/FileStore.java
- src/main/java/com/adobe/testing/s3mock/domain/MultipartUploadInfo.java
- src/main/java/com/adobe/testing/s3mock/dto/ListMultipartUploadsResult.java
- src/main/java/com/adobe/testing/s3mock/dto/MultipartUpload.java
- src/test/java/com/adobe/testing/s3mock/domain/FileStoreTest.java
- src/test/java/com/adobe/testing/s3mock/its/AmazonClientUploadIT.java
Hey guys, here's an MVP solution for listing multipart uploads (#15), where all in-progress multipart uploads are returned. I.e. several request parameters are not yet supported: delimiter, encoding-type, max-uploads, key-marker, prefix, upload-id-marker.
Additionally this brings support for aborting a multipart upload.
> Adds abort-multipart-upload + simple support for list-multipart-uploads

- pom.xml
- src/main/java/com/adobe/testing/s3mock/domain/FileStore.java
Jackson is already shipped with Spring Boot, so we can reuse it instead of introducing a new JSON dependency. Jackson also provides an API which allows to work with JSON objects represented as `File` without converting them to streams or strings.
> Remove a Gson dependency

- pom.xml
Not all users use JUnit as their test framework. There are people who use JUnit5, TestNG or Spock. We need JUnit only for `S3Rule`, which is optional.
> Mark JUnit as an optional dependency

- pom.xml
- src/main/java/com/adobe/testing/s3mock/FileStoreController.java
- src/main/java/com/adobe/testing/s3mock/domain/BucketContents.java
- src/main/java/com/adobe/testing/s3mock/dto/CopyPartResult.java
- src/main/java/com/adobe/testing/s3mock/util/AwsChunkDecodingInputStream.java
- src/main/java/com/adobe/testing/s3mock/util/BetterHeaders.java
- src/test/java/com/adobe/testing/s3mock/dto/CopyPartResultTest.java
There's a ton of different versions of the Java S3 SDK [1} . A version is used at the client side is most certainly will not match with the version declared in S3Mock. In case if the library integrated to a
Java application via Maven/Gradle, the developer will have to exclude the aws-java-sdk-s3 dependency or to be at mercy of the default version resolution process in the dependency manager.
It makes sense to declare the dependency as optional and isolate it to `S3MockRule`. In this case the dependency manager will pick up the version of the client SDK. In case the server is run as a Docker
container, we will not add the library to the a distribution, because
the server doesn't depend on it.
[1]: https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-s3
> Isolate the aws-java-sdk-s3 dependency to S3MockRule

- src/main/java/com/adobe/testing/s3mock/util/RangeConverter.java
- src/test/java/com/adobe/testing/s3mock/RangeConverterTest.java
Hi There,
Please take a look at this PR, which fixes the issue where in GetObject request with byte range of format 10- (starting from 10 to the end of file).
Didn't find any test case to test controller , so tested manually.
Regards,
Syed Frahan Ali
> handle case where where end range is undefined

- src/main/java/com/adobe/testing/s3mock/FileStoreController.java
- src/main/java/com/adobe/testing/s3mock/domain/FileStore.java
- src/main/java/com/adobe/testing/s3mock/domain/S3Object.java
- src/test/java/com/adobe/testing/s3mock/its/AmazonClientUploadIT.java
This is an MVP version for user-defined metadata support (headers starting
with "x-amz-meta-"). User metadata is read in `putObject` and returned
with `headObject` or `getObject`.
More support for user-defined metadata (like e.g. for multipart uploads etc)
would have to be added with separate PRs.
> Adds support for user metadata for putObject / headObject

- src/main/java/com/adobe/testing/s3mock/FileStoreController.java
- src/main/java/com/adobe/testing/s3mock/domain/FileStore.java
- src/main/java/com/adobe/testing/s3mock/domain/MultipartUploadInfo.java
- src/test/java/com/adobe/testing/s3mock/its/AmazonClientUploadIT.java
- support for user metadata was added already but could only be set by putObject
- now initiateMultipartUpload as well reads headers starting with "x-amz-meta-".
> Complete support for user metadata including putObjectEncrypted and multipart upload

- pom.xml
To support Java 9, JAXB needs to be added to the module path.
> Adding support for Java 9

- README.md
- testsupport/common/src/main/java/com/adobe/testing/s3mock/testsupport/common/S3MockStarter.java
- testsupport/testng/src/test/java/com/adobe/testing/s3mock/testng/S3MockListenerXMLConfigurationTest.java
Adding optional region parameter to createS3Client method
#55
> Adding optional region to client creation

- pom.xml
- server/src/main/java/com/adobe/testing/s3mock/S3MockApplication.java
- testsupport/junit4/pom.xml
Spring Sec. Filters avoid invocations of S3 Mocks API- 
https://github.com/adobe/S3Mock/issues/59
> excludes SecurityAutoConfiguration

- build-config/pom.xml
The build-config module needs to be of type `jar` after all... My bad @timoe.
> Fix finding checkstyle config

- server/src/main/java/com/adobe/testing/s3mock/domain/FileStore.java
- server/src/test/java/com/adobe/testing/s3mock/domain/FileStoreTest.java
- server/src/test/java/com/adobe/testing/s3mock/its/AmazonClientUploadIT.java
When completing the multipart upload, file parts are sorted by their part number to not corrupt the file.
Fixes https://github.com/adobe/S3Mock/issues/65
Fixes https://github.com/adobe/S3Mock/issues/67
---
@agudian: Please review, merge + rebase
>  Fix lexical sorting for Multipart Upload

- .github/CONTRIBUTING.md
- README.md
- proper link to CONTRIBUTING.md from README
- link to open source office email in CONTRIBUTING.md
- removed "probably" from CONTRIBUTING.md with respect to CLA signing - better to get rid of vague sentences!
> 📝 README and CONTRIBUTING doc tweaks

- server/src/test/java/com/adobe/testing/s3mock/domain/FileStoreTest.java
Fix shouldGetEncryptedObject and shouldStoreObjectEncrypted test from FileStoreTest for Windows
In tests methods shouldGetEncryptedObject and shouldStoreObjectEncrypted of FileStoreTest class you are using hardcoded "SIGNED_CONTENT" which includes Linux style line ending. But for verification before this change you have used contents of the "src/test/resources/sampleFile.txt" file. So if I clone this git repo on Windows I will get this file with Windows style line endings. As a result md5 verification on Windows will fail. Since you are using hard coded "SIGNED_CONTENT" I've added hard coded "UNSIGNED_CONTENT" which does not depend on OS line ending.
> Fix shouldGetEncryptedObject and shouldStoreObjectEncrypted test from FileStoreTest for Windows

- server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
jclouds library fails its "getBlob" operation if there is no Last-Modified header. This commit adds this header. 
https://github.com/adobe/S3Mock/issues/32
> Added Last-modified header to getObject operation response

- server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
- server/src/main/java/com/adobe/testing/s3mock/S3MockApplication.java
- server/src/main/java/com/adobe/testing/s3mock/dto/ListBucketResultV2.java
- server/src/test/java/com/adobe/testing/s3mock/its/AmazonClientUploadIT.java
Without this change only V1 (http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGET.html) API is supported. V2 adds pagination support. See http://docs.aws.amazon.com/AmazonS3/latest/API/v2-RESTBucketGET.html 
I have added new endpoint to FileStoreController which is responsible for V2 requests. Corresponding integration test is also added. In addition to this I have tested my implementation using AWS s3 sdk version 2.0.0.preview-10
https://github.com/adobe/S3Mock/issues/7
> Support GET Bucket (List Objects) Version 2

- server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
- server/src/main/java/com/adobe/testing/s3mock/domain/FileStore.java
- server/src/main/java/com/adobe/testing/s3mock/dto/CommonPrefixes.java
- server/src/main/java/com/adobe/testing/s3mock/dto/ListBucketResult.java
- server/src/main/java/com/adobe/testing/s3mock/dto/ListBucketResultV2.java
- server/src/test/java/com/adobe/testing/s3mock/its/AmazonClientUploadIT.java
- server/src/test/java/com/adobe/testing/s3mock/its/ListObjectIT.java
Add support for `delimiter` parameter to the ListObjects and ListObjectsV2 APIs
#89
> Add support for the delimiter parameter to the List Objects API

- server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
- server/src/test/java/com/adobe/testing/s3mock/its/AmazonClientUploadIT.java
"Content-Range" header should contain the complete-length of the body in response to a request with "Range" header.
S3 also returns Content-Range header with  the complete-length and `ObjectMetadata.getInstanceLength()` in AWS SDK for Java depends on it.
RFC 7233 says 
>For byte ranges, a sender SHOULD indicate the complete length of the
representation from which the range has been extracted, unless the
complete length is unknown or difficult to determine.
https://tools.ietf.org/html/rfc7233#section-4.2
> Content-Range value should contain complete-length

- server/src/main/java/com/adobe/testing/s3mock/domain/FileStore.java
- server/src/test/java/com/adobe/testing/s3mock/domain/FileStoreTest.java
- server/src/test/java/com/adobe/testing/s3mock/its/ListObjectIT.java
Based on https://aws.amazon.com/blogs/compute/amazon-s3-adds-prefix-and-suffix-filters-for-lambda-function-triggering/
This should allow filtering by partial filenames
To address: https://github.com/adobe/S3Mock/issues/97
- validate that the functionality matches real S3
- run the tests
- ???
- profit
> Matching real S3 partial prefix matching

- server/src/main/java/com/adobe/testing/s3mock/S3MockApplication.java
- testsupport/common/src/main/java/com/adobe/testing/s3mock/testsupport/common/S3MockStarter.java
- testsupport/junit5/src/test/java/com/adobe/testing/s3mock/junit5/S3MockExtensionProgrammaticTest.java
Allow the s3 client to communicate over HTTP or HTTPS connections.
Fixes #95
> Allow the s3 client to communicate over HTTP or HTTPS connections.

- server/src/main/java/com/adobe/testing/s3mock/dto/InitiateMultipartUploadResult.java
- server/src/test/java/com/adobe/testing/s3mock/its/AmazonClientUploadIT.java
Renamed bucket name's alias to "Bucket" according to https://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadInitiate.html
#102
> Fixed alias for bucket name in InitiateMultipartUploadResult

- server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
- server/src/test/java/com/adobe/testing/s3mock/its/ListObjectIT.java
Fix common prefix for listObjectsV2 request.
Otherwise a NPE was thrown.
> Fix common prefix for listObjectsV2 request.

- server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
- server/src/main/java/com/adobe/testing/s3mock/dto/ListBucketResult.java
- server/src/test/java/com/adobe/testing/s3mock/its/ListObjectV1MaxKeysIT.java
The implementations of the List Objects V1 API doesn't honor the `max-keys` parameters of `ListObjectsRequest`. It would be nice if s3-mock supported it to reduce the disparity with the features provided by the actual S3 service.
Docs: https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGET.html
Fixes #99
> Honor max-keys parameter in List Objects v1 API

- pom.xml
- server/src/main/java/com/adobe/testing/s3mock/S3MockApplication.java
- server/src/main/resources/application.properties
- server/src/test/java/com/adobe/testing/s3mock/its/PlainHttpIT.java
- When handling requests without a content type, support unmarshalling the XML payload
- Update JDK, SpringBoot and AWS SDK version to latest.
fixes #87
> #87 Fix handling requests without content type

- server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
- server/src/test/java/com/adobe/testing/s3mock/its/PlainHttpIT.java
The s3mock doesn't work correctly for the [Characters That Might Require Special Handling ](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#object-keys) those characters are not supported.
https://github.com/adobe/S3Mock/issues/119
> fixed inconsistent file name encoding

- server/src/main/java/com/adobe/testing/s3mock/dto/ObjectRef.java
- server/src/test/java/com/adobe/testing/s3mock/its/AmazonClientUploadIT.java
Fix issue #131
#131
- [?] I have written tests and verified that they fail without my change.
Important - why did I place a ? in the checkbox above? There seems to be an issue with the tests run via the maven lifecycle. The build succeeds despite failing tests. And this doesn't seem to apply to my newly introduced tests only, but also to `AmazonClientUploadIT.defaultBucketsGotCreated()` and others. To reveal the failing tests I started `S3MockApplication` within the IDE then ran `AmazonClientUploadIT`. This revealed the (expected) failure of my new test as well as the others.
My newly introduced tests succeed, of course, but the aforementioned others still fail when run as described above.
> Fix #131: apply URL-decoding to the copy source

- server/src/main/java/com/adobe/testing/s3mock/S3MockApplication.java
- testsupport/junit4/pom.xml
Exclude `org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration` by class name, in order to prevent an erroneous `CsrfFilter` activation.
#130 
Please note that this time there is no dedicated test case. Instead, `s3mock-junit4`'s POM was modified to include `spring-boot-starter-actuator` which triggers the issue.
> Fix #130: exclude ManagementWebSecurityAutoConfiguration by class name

- AUTHORS
- pom.xml
- testsupport/common/pom.xml
- testsupport/common/src/main/java/com/adobe/testing/s3mock/testsupport/common/S3MockStarter.java
- testsupport/junit5/src/main/java/com/adobe/testing/s3mock/junit5/S3MockExtension.java
- testsupport/junit5/src/test/java/com/adobe/testing/s3mock/junit5/sdk1/S3MockExtensionDeclarativeTest.java
- testsupport/junit5/src/test/java/com/adobe/testing/s3mock/junit5/sdk1/S3MockExtensionProgrammaticTest.java
- testsupport/junit5/src/test/java/com/adobe/testing/s3mock/junit5/sdk2/S3MockExtensionDeclarativeTest.java
- testsupport/junit5/src/test/java/com/adobe/testing/s3mock/junit5/sdk2/S3MockExtensionProgrammaticTest.java
Amazon released some time ago version 2 of their SDK. This PR adds support for it under JUnit 5.
In case that would be a blocker, I should probably be able to add it to the other test environment too.
Unrelated question: Why is the CLA website only reachable over http?
> Add AWS SDK 2.0 support for JUnit 5

- server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
- server/src/test/java/com/adobe/testing/s3mock/its/ListObjectIT.java
continuation token is now mapped to key in order to be able to get correct elements in case of removals/uploads.
start after was also fixed to work properly (esp. in case of missing key)
also continuation token and start after now share processing and follow Amazon's "This parameter is valid only in your first request. If the response is truncated, you can specify this parameter along with the continuation-token parameter, and then Amazon S3 ignores this parameter."
Fixes #112: continuation token and start after
> Fixes #112: continuation token and start after

- server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
- server/src/main/java/com/adobe/testing/s3mock/domain/FileStore.java
- server/src/main/java/com/adobe/testing/s3mock/domain/MultipartUploadInfo.java
- server/src/main/java/com/adobe/testing/s3mock/domain/S3Object.java
- server/src/test/java/com/adobe/testing/s3mock/domain/FileStoreTest.java
- server/src/test/java/com/adobe/testing/s3mock/its/AmazonClientUploadIT.java
`Content-Encoding` was completely missing.
- added content-encoding field
- cleaned up some content-type issues
- modified tests for check of the new functionality
Fixes #145: `Content-encoding` support is missing
> Fixes #145: `Content-encoding` support is missing

- server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
- server/src/test/java/com/adobe/testing/s3mock/its/AmazonClientUploadIT.java
* add extraction of tags from request to putObject() and putObjectEncrypted()
* add integration test to show it working
should handle #142
> accept object tagging via PutObject requests

- AUTHORS
- pom.xml
- server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
- server/src/main/java/com/adobe/testing/s3mock/domain/FileStore.java
- server/src/main/java/com/adobe/testing/s3mock/dto/ListPartsResult.java
- server/src/main/java/com/adobe/testing/s3mock/dto/Part.java
- server/src/test/java/com/adobe/testing/s3mock/domain/FileStoreTest.java
- server/src/test/java/com/adobe/testing/s3mock/its/AmazonClientUploadIT.java
To adapt to Amazon's S3 behaviour this pull request introduces an implementation of retrieving parts of a prepared S3 MultiPart upload.
**What the pull request includes:**
- new `parts` attribute in `ListPartsResult.java` DTO
- new `Part` class for representing a single S3 MultiPartUpload part
- Functionality getMultipartUploadParts in `FileStore.java` for retrieving the uploaded parts in the directory of the uploaded file
- encapsulation of `File` access in `FileStore.java` via `java.nio.file.Paths`
- Unit Test for retrieving upload parts of a S3 multipart upload (Chunked in 2 parts) -> Build upon `prepareMultipartUpload`
> Retrieval of MultiPart upload parts

- AUTHORS
- pom.xml
- server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
- server/src/test/java/com/adobe/testing/s3mock/its/AmazonClientUploadIT.java
Adds support for response header overrides according to https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectGET.html#RESTObjectGET-requests
> Adds support for response header overrides

- server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
Changed requirements of putObjectEncrypted to not match copy requests.
> Fixed ambuguity of encrypted copy requests.

- server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
- server/src/main/java/com/adobe/testing/s3mock/domain/FileStore.java
- server/src/test/java/com/adobe/testing/s3mock/its/AmazonClientUploadIT.java
- server/src/test/java/com/adobe/testing/s3mock/its/S3TestBase.java
The problem was that the code incorrectly assumed that anything signed with a V4 SHA signature is also using the V4 chunked encoding. That's fixed now, and a test was added to check uploading a file with all combinations of signing and chunking enabled/disabled.
Fixes #107, fixes #121, fixes #147.
> #121 Fix handling of V4 signed requests that don't use chunking.

- server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
- server/src/test/java/com/adobe/testing/s3mock/its/PlainHttpIT.java
This fixes a bug that occurs with e.g. boto3 when you list objects in a bucket.
The problem is that the S3Mock expects a listObject request to end with a trailing slash like `127.0.0.1:9090/my-bucket/?prefix=foo%2F&encoding-type=url`.
Unfortunately boto3 will send a request like this: `127.0.0.1:9090/my-bucket?prefix=foo%2F&encoding-type=url`
This changes fixes that behaviour and adds a test to verify it (before a 500 response would be thrown)
> Fixed list without trailing slash (eg. boto3)

- server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
- server/src/main/java/com/adobe/testing/s3mock/dto/ListBucketResult.java
- server/src/test/java/com/adobe/testing/s3mock/its/ListObjectIT.java
- server/src/test/java/com/adobe/testing/s3mock/its/ListObjectV1PaginationIT.java
Honor **Marker**, **NextMarker** and **IsTruncated** parameters to enable pagination while listing objects
https://github.com/adobe/S3Mock/issues/166
> Honor Marker, NextMarker and IsTruncated parameters in List Objects v1 API

- server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
- server/src/main/java/com/adobe/testing/s3mock/KmsValidationFilter.java
- server/src/main/java/com/adobe/testing/s3mock/domain/FileStore.java
- server/src/main/java/com/adobe/testing/s3mock/domain/S3Object.java
- server/src/main/java/com/adobe/testing/s3mock/util/AwsHttpHeaders.java
- server/src/main/java/com/adobe/testing/s3mock/util/MetadataUtil.java
- server/src/test/java/com/adobe/testing/s3mock/its/AmazonClientUploadIT.java
1. Copying user-metadata based on **x-amz-metadata-directive** header.
2. Refactored metadata related functionality to a separate class `MetadataUtil`
- For header value **REPLACE**, all the content metadata specified through headers (like _content-type_, _cache-control_, _content-encoding_ etc.,) also needs to be replaced not only user-metadata, that would require a bit of refactoring (due to the way in which code is organised currently), can be taken as a separate check-in. In case of **COPY**, source metadata has to be copied which is happening by default already.
Ref: https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectCOPY.html
#124 - Issue talks about CopyPart API, although this PR address CopyObject API
> Honoring x-amz-metadata-directive in CopyObject API

- server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
- server/src/test/java/com/adobe/testing/s3mock/its/AmazonClientUploadIT.java
- server/src/test/java/com/adobe/testing/s3mock/its/S3TestBase.java
Non-Empty bucket should not be deleted
Ref: https://docs.aws.amazon.com/AmazonS3/latest/dev/delete-or-empty-bucket.html#delete-bucket
#120
> Non-Empty bucket should not be deleted

- .travis/travis-release.sh
- AUTHORS
- CODE_OF_CONDUCT.md
- README.md
Amended the following documents:
- Readme
- Code-of-conduct
- travis-release.sh
To add in some missed punctuation within comments and the aforementioned documentation
N/A
> Neatened up documentation punctuation

- .travis.yml
Travis release says
```
Installing oraclejdk8
$ export JAVA_HOME=~/oraclejdk8
$ export PATH="$JAVA_HOME/bin:$PATH"
$ ~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"
Ignoring license option: BCL -- using GPLv2+CE by default
install-jdk.sh 2019-09-17
Expected feature release number in range of 9 to 14, but got: 8
The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .
Your build has been stopped.
```
Using workaround from https://travis-ci.community/t/install-of-oracle-jdk8-is-failing/4365 might help?
> using dist:thrusty as a workaround for travis release

- pom.xml
- server/src/main/java/com/adobe/testing/s3mock/domain/FileStore.java
- server/src/test/java/com/adobe/testing/s3mock/its/ListObjectIT.java
also includes changes to be able to run javadoc on java 11
Fixes normalization of the prefix
Fixes #181
> Fixes #181: Listing bucket with a prefix can give wrong results

- server/src/main/java/com/adobe/testing/s3mock/KmsValidationFilter.java
- server/src/test/java/com/adobe/testing/s3mock/its/PlainHttpIT.java
If request header `x-amz-server-side-encryption:aws:kms` is given, but `x-amz-server-side-encryption-aws-kms-key-id` isn't, the request will be accepted.
https://github.com/adobe/S3Mock/issues/190
> kms-key-ref can be empty

- README.md
- build-config/src/main/resources/build-config/checkstyle.xml
- server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
- server/src/main/java/com/adobe/testing/s3mock/dto/Owner.java
- server/src/main/java/com/adobe/testing/s3mock/util/MetadataUtil.java
- server/src/test/java/com/adobe/testing/s3mock/its/AmazonClientUploadIT.java
- testsupport/common/src/main/java/com/adobe/testing/s3mock/testsupport/common/S3MockStarter.java
This PR fixes some spelling errors (mostly code comments, test descriptions, etc.), IMHO a purely cosmetic/non-functional change.
commmon -> common (2x)
congiguration -> configuration (2x)
declaritive -> declarative (1x)
interace -> interface (1x)
listinig -> listing (1x)
matchin -> matching (2x)
requrements -> requirements (1x)
requeting -> requesting (2x)
retrives -> retrieves (1x)
ther -> the (1x)
vaule -> value (2x)
wich -> with (2x)
n/a
This PR is purely cosmetic => adding a test doesn't apply. In general, one could add a (source code-aware) spell checker to the CI test suite.
> Fix some spelling errors.

- server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
- server/src/test/java/com/adobe/testing/s3mock/its/PlainHttpIT.java
Some of the S3Mock endoints return a `application/x-www-form-urlencoded` Content-Type, which is ignored by most clients but is HTTP specification wise not correct. The AWS API spec doesn't explicitly describe the Content-Type, but the the actual response body is XML and the Content-Type `application/octet-stream`
Some strict clients (e.g. Akka HTTP, Alpakka), correctly reject parsing a Content-Type of `application/x-www-form-urlencoded` as XML, but rather expect `application/octet-stream` or `application/xml`.
I've tried changing the Content-Type to `application/octet-stream`, but the Spring Framework always returns a `400 - Bad Request` then in the IT tests. I couldn't figure out why, but my guess is that it doesn't know that this response should be marshalled XML. Changing the …
> More Specific Response Content Type

- server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
Strip double quotes from e-tag during CompleteMultipart validation
#223
> Strip double quotes from e-tag during CompleteMultipart validation

- .editorconfig
- pom.xml
https://editorconfig.org/ is recognized by many editors and IDEs, so it would be great if the project would configure IDE automatically.
> Add .editorconfig so IDE code style is configured automatically

- testsupport/common/src/main/java/com/adobe/testing/s3mock/testsupport/common/S3MockStarter.java
`S3MockServer#getServiceEndpoint()`  is useful for programmatic API.
https://github.com/adobe/S3Mock/issues/232
> Make S3MockServer#getServiceEndpoint() public

- pom.xml
Source/Target parameters were deprecated in JDK8 and can cause errors when running bytecode compiled in JDK9+ on JDKs lower than JDK9.
Use newly added `release` parameter instead.
See #243 where @HackerTheMonkey analysed this issue pretty thoroughly, and the official documentation:
https://docs.oracle.com/en/java/javase/11/migrate/index.html#JSMIG-GUID-77874D97-46F3-4DB5-85E4-2ACB5F8D760B
Fixes #243
> Fix accidental JDK9+ bytecode dependency

- server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
- server/src/main/java/com/adobe/testing/s3mock/dto/ListBucketResult.java
- server/src/main/java/com/adobe/testing/s3mock/dto/ListBucketResultV2.java
- server/src/test/java/com/adobe/testing/s3mock/its/ListObjectIT.java
This PR adds the encoding type in the return of the ListObjects and ListObjectsV2.
It's adding some tests for verifying that the encoding type is null if not specified or "url" if it is specified.
https://github.com/adobe/S3Mock/issues/199
> Add encodingType as return parameter of ListObjects and ListObjectsV2

- AUTHORS
- server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
- server/src/main/java/com/adobe/testing/s3mock/dto/ListBucketResult.java
- server/src/main/java/com/adobe/testing/s3mock/dto/ListBucketResultV2.java
- server/src/test/java/com/adobe/testing/s3mock/its/ListObjectIT.java
aws-cli expects no empty elements in encoded responses and will fail
the request if it encounters an empty element.
At least aws-java-sdk V1 and V2 worked fine with the current
implementation, though.
Add Arne Franken to AUTHORS
#257
> Fix encoded responses for aws-cli

- pom.xml
- server/pom.xml
- server/src/main/java/com/adobe/testing/s3mock/dto/MultipartUpload.java
- server/src/main/java/com/adobe/testing/s3mock/dto/Part.java
- server/src/test/java/com/adobe/testing/s3mock/dto/BatchDeleteResponseTest.java
- server/src/test/java/com/adobe/testing/s3mock/dto/CompleteMultipartUploadResultTest.java
- server/src/test/java/com/adobe/testing/s3mock/dto/CopyObjectResultTest.java
- server/src/test/java/com/adobe/testing/s3mock/dto/DtoTestUtil.java
- server/src/test/java/com/adobe/testing/s3mock/dto/ErrorResponseTest.java
- server/src/test/java/com/adobe/testing/s3mock/dto/InitiateMultipartUploadResultTest.java
- server/src/test/java/com/adobe/testing/s3mock/dto/ListAllMyBucketsResultTest.java
- server/src/test/java/com/adobe/testing/s3mock/dto/ListBucketResultTest.java
- server/src/test/java/com/adobe/testing/s3mock/dto/ListBucketResultV2Test.java
- server/src/test/java/com/adobe/testing/s3mock/dto/ListMultipartUploadsResultTest.java
- server/src/test/java/com/adobe/testing/s3mock/dto/ListPartsResultTest.java
- server/src/test/resources/com/adobe/testing/s3mock/dto/BatchDeleteResponseTest_testSerialization.xml
- server/src/test/resources/com/adobe/testing/s3mock/dto/CompleteMultipartUploadResultTest_testSerialization.xml
- server/src/test/resources/com/adobe/testing/s3mock/dto/CopyObjectResultTest_testSerialization.xml
- server/src/test/resources/com/adobe/testing/s3mock/dto/CopyPartResultTest_testSerialization.xml
- server/src/test/resources/com/adobe/testing/s3mock/dto/ErrorResponseTest_testSerialization.xml
- server/src/test/resources/com/adobe/testing/s3mock/dto/InitiateMultipartUploadResultTest_testSerialization.xml
- server/src/test/resources/com/adobe/testing/s3mock/dto/ListAllMyBucketsResultTest_testSerialization.xml
- server/src/test/resources/com/adobe/testing/s3mock/dto/ListBucketResultTest_testSerialization.xml
- server/src/test/resources/com/adobe/testing/s3mock/dto/ListBucketResultV2Test_testSerialization.xml
- server/src/test/resources/com/adobe/testing/s3mock/dto/ListMultipartUploadsResultTest_testSerialization.xml
- server/src/test/resources/com/adobe/testing/s3mock/dto/ListPartsResultTest_testSerialization.xml
This only adds tests and serialized responses to see what changes when
refactoring the code.
There are several issues with the current serialization:
Typos in fields. (e.g. "prefix" instead of "Prefix")
Superfluous fields (e.g. "truncated" or "part")
Some lists are not serialized correctly, as can be seen in
currently open issues.
Several types are not enforced, where fields in the POJOs are Strings
which should be Integer or enum.
Etag fields contain quoted values in all Amazon examples, while in
our serialization, they are all unquoted.
Date field serialization seems to be broken right now. Also, for dates,
we should be using "java.time" classes in favor of "java.util.Date".
There are several issues dealing with serialization issues, e.g. #215
> Adds serialization tests for the DTO layer

- .github/workflows/create-release-from-tag.yml
- CHANGELOG.md
The tag is pushed by our Maven release.
Version headings in CHANGELOG.md must match tag pattern.
N/A
> Set a new Github release on tag push

- server/src/main/java/com/adobe/testing/s3mock/domain/FileStore.java
All files that are created by a JVM need to be registered separately to
be deleted on exit. Simply registering the S3Mock root does not suffice.
Unfortunately, this only works when the JVM is shut down in an orderly
fashion.
If the JVM crashes, or if the Docker container crashes, there is no way
for us to delete the files uploaded to the S3Mock.
This was easily reproduced by running `com.adobe.testing.s3mock.junit5.sdk2.S3MockExtensionDeclarativeTest` from the IDE. This left all test files in my tmp directory:
```
/var/folders/ll/l9wcy04j4ssfm2cb7zxkp5hh0000gn/T>
ls s3mockFileStore1625647*
s3mockFileStore1625647422582:
./                ../               mydemotestbucket/
s3mockFileStore1625647575190:
./                ../               mydemotestbucket/
s3mockFileStore1625647731348:
./ …
```
> Delete all files on JVM shutdown

- CHANGELOG.md
- README.md
- docker/pom.xml
- integration-tests/pom.xml
- pom.xml
Docker build is now optional.
Run with "-DskipDocker" if you want to build the code only.
Fixes #235
> Optional integration tests and docker build

- pom.xml
With version 4.x, the license-maven-plugin checks the GIT history of a
file to determine when a file was created. This does not work on the GIT
clone the maven-release-plugin is creating just for the release.
We check the headers in the PRB _and_ in the "main" build after a PR is
merged. No need to check license headers again during a release.
N/A
> Disable license header checks during maven release

- integration-tests/src/test/java/com/adobe/testing/s3mock/its/MultiPartUploadIT.java
- server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
- server/src/main/java/com/adobe/testing/s3mock/domain/FileStore.java
- server/src/main/java/com/adobe/testing/s3mock/dto/ObjectRef.java
Adds integration tests for CopyParts API.
APIs must return "application/xml".
Incoming key reference must undergo decode&encode cycle just like the
destinationFile name we take from the incoming request path. ObjectRef
now does this for every incoming request. Before, clients of ObjectRef
would need to remember to encode the key again before usage. D'OH!
From/To values are of type "long" in the request, not "int". Copying
of parts larger than Integer.MAX_VALUE would have failed.
Special thanks to user @wwelling for spotting these issues and providing
the fix, I just refactored and added an integration test.
fixes #279, makes #278 obsolete.
> Fixes copy part / copy object encoding issues

- docker/src/main/docker/Dockerfile
Overriding the root folder thanks to the environment variable `root` in Docker container was not possible because of java system property (-D).
Moving this default value to environment variable solve the issue.
No related issue.
> Move root folder to environment variable docker

- server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
Adds CORS support (for any domain) to the files stored in s3mock, this allows browser based clients to connect to the s3mock server. (e.g. via pre-signed URLs)
Can't really write ITs for this as I don't have docker installed.
#74 Support for CORS headers
> Support for CORS headers on bucket contents

- testsupport/common/pom.xml
- testsupport/common/src/test/java/com/adobe/testing/s3mock/testsupport/common/S3MockStarterTest.java
Not sure why the test was empty before.
S3MockStarter just adds a bit of convenience by providing a
preconfigured S3Client instance.
#275
> Test startup and shutdown of S3MockApplication

- integration-tests/src/test/java/com/adobe/testing/s3mock/its/MultiPartUploadIT.java
- server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
- server/src/main/java/com/adobe/testing/s3mock/domain/FileStore.java
- server/src/main/java/com/adobe/testing/s3mock/domain/MultipartUploadInfo.java
- server/src/test/java/com/adobe/testing/s3mock/domain/FileStoreTest.java
Multipart uploads now support buckets.
#292
> Set bucket for multipart uploads, return by bucket.

- server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
Remove duplicate CORS header in get object.
#74
> Remove duplicate CORS header in get object.

- integration-tests/src/test/java/com/adobe/testing/s3mock/its/AmazonClientUploadIT.java
- server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
- server/src/main/java/com/adobe/testing/s3mock/store/FileStore.java
- server/src/main/java/com/adobe/testing/s3mock/store/S3Object.java
- server/src/main/java/com/adobe/testing/s3mock/util/AwsChunkedDecodingInputStream.java
- server/src/main/java/com/adobe/testing/s3mock/util/AwsHttpHeaders.java
- server/src/main/java/com/adobe/testing/s3mock/util/DigestUtil.java
- server/src/test/java/com/adobe/testing/s3mock/FileStoreControllerTest.java
- server/src/test/java/com/adobe/testing/s3mock/store/FileStoreTest.java
- testsupport/junit4/src/test/java/com/adobe/testing/s3mock/junit4/S3MockRuleTest.java
- testsupport/junit5/pom.xml
- testsupport/junit5/src/test/java/com/adobe/testing/s3mock/junit5/sdk1/S3MockExtensionDeclarativeTest.java
- testsupport/junit5/src/test/java/com/adobe/testing/s3mock/junit5/sdk1/S3MockExtensionProgrammaticTest.java
- testsupport/junit5/src/test/java/com/adobe/testing/s3mock/junit5/sdk2/S3MockExtensionDeclarativeTest.java
- testsupport/junit5/src/test/java/com/adobe/testing/s3mock/junit5/sdk2/S3MockExtensionProgrammaticTest.java
- testsupport/testcontainers/src/test/java/com/adobe/testing/s3mock/testcontainers/S3MockContainerTestBase.java
- testsupport/testng/pom.xml
- testsupport/testng/src/test/java/com/adobe/testing/s3mock/testng/S3MockListenerXmlConfigurationTest.java
Fixed etag handling. Not sure why this was all mixed with MD5 handling.
Added Content-MD5 handling.
#208
> Add Content-MD5 header handling

- server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
- server/src/main/java/com/adobe/testing/s3mock/S3MockApplication.java
- server/src/main/java/com/adobe/testing/s3mock/S3MockProperties.java
- server/src/test/java/com/adobe/testing/s3mock/ContextPathFileStoreControllerTest.java
See subject.
Closing #384 in favor of this PR - I could not push changes to @arpluta s branch.
N/A
> Make contextPath of FileStoreController configurable

- integration-tests/src/test/java/com/adobe/testing/s3mock/its/AmazonClientUploadIT.java
- integration-tests/src/test/java/com/adobe/testing/s3mock/its/ErrorResponsesIT.java
- integration-tests/src/test/java/com/adobe/testing/s3mock/its/S3TestBase.java
- server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
- server/src/test/java/com/adobe/testing/s3mock/FileStoreControllerTest.java
AWS allows multipart uploads only if all parts (but the last) are at
least 5MB in size. All tests were using payloads that are too small,
mis-configured TransferManager instances cutting the payloads in parts
that are below 5MB in size.
#392
> Add multi-part upload checks, S3 has a minimum size allowed of 5MB

- docker/build-docker-image.sh
- docker/pom.xml
- docker/push-docker-image.sh
- docker/start-buildkit.sh
- docker/stop-buildkit.sh
- pom.xml
This supports linux/amd64 and linux/arm64 for now.
Fixes #253 #287 #389
> Use "docker buildx" for multi-platform builds.

- docker/pom.xml
- docker/push-docker-image.sh
- pom.xml
See subject.
Changes merged in #403 work during regular builds, but fail during release.
Duplicating the build steps fully in the release profile now.
#403
> Build and publish in "push-docker-image" profile

- docker/Dockerfile
Currently, the Docker image entrypoint is in the shell form. Changing it to the exec form allows to run the Docker image with additional arguments, like the server port, without having to redefine the whole command.
See https://docs.docker.com/engine/reference/builder/#entrypoint
- [ X ] I have signed the [CLA](http://adobe.github.io/cla.html).
- [ X ] I have written tests and verified that they fail without my change.
> Change Docker image entrypoint to exec form

- server/src/main/java/com/adobe/testing/s3mock/S3MockApplication.java
- server/src/main/java/com/adobe/testing/s3mock/store/DomainProperties.java
- server/src/main/resources/application.properties
- testsupport/pom.xml
- testsupport/testcontainers/src/main/java/com/adobe/testing/s3mock/testcontainers/S3MockContainer.java
Manually translate legacy to new property names.
When starting the S3Mock directly from Java with an 
"application.properties" in the  classpath, the S3Mock's bundled 
"application.properties" is not found anymore, so we can't do property 
translation there.
Implementing a poor man's property translation that directly interferes
with Spring's "Externalized Properties" precedence order here.
Need to deprecate direct usage and remove this ASAP.
"Fixes" #434
Probably breaks other integrations, we'll see...
#434
> 434 fix property overrides

- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/AmazonClientUploadIT.kt
- server/src/main/java/com/adobe/testing/s3mock/store/FileStore.java
This implementation just fakes the copy process - there currently is no
way to change particular metadata of an existing key in the FileStore.
Fixes #468
> Allow "copy" of key to same key.

- server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
- server/src/test/java/com/adobe/testing/s3mock/FileStoreControllerTest.java
Given PR adds missing `x-amz-server-side-encryption` and `x-amz-server-side-encryption-aws-kms-key-id` headers to the getObject and headObject responses.
**Problem statement:** Currently S3Mock doesn't return these headers in the getObject response (and partially returns in the headObject one). This leads to the exception to be thrown during the object integrity validation by AWS SDK while downloading encrypted object via getObject requests as `x-amz-server-side-encryption-aws-kms-key-id` header is used in the [SkipMd5CheckStrategy](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/SkipMd5CheckStrategy.java#L304-L310). 
Without this header object's etag value is compared to the InputStream digest and validation fails as etag …
> Adds missing x-amz-server-side-encryption and x-amz-server-side-encryption-aws-kms-key-id header

- pom.xml
This fixes various serious security issues by updating transitive dependencies.
https://github.com/sonatype/nexus-maven-plugins/pull/91
> Bump nexus-staging-maven-plugin to 1.6.13

- docker/build-docker-image.sh
- docker/pom.xml
- docker/push-docker-image.sh
- docker/start-buildkit.sh
- docker/stop-buildkit.sh
- pom.xml
Reverts adobe/S3Mock#617
docker-maven-plugin's `docker:push` target is still broken, this is only invoked during a release...
https://github.com/adobe/S3Mock/runs/6901658834?check_suite_focus=true
> Revert "Revert build to docker-maven-plugin with buildx"

- CHANGELOG.md
- docker/Dockerfile
While connections from Java and Python AWS SDKs work, "aws-cli" does not.
Fixes #706
> Add module "jdk.crypto.ec" to fix SSL handshake

- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/MultiPartUploadIT.kt
- server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
- server/src/main/java/com/adobe/testing/s3mock/store/FileStore.java
- server/src/test/java/com/adobe/testing/s3mock/FileStoreControllerTest.java
Allow listing a MultiPartUpload with no parts.
This was introduced with #397
Fixes #694
> Allow listing a MultiPartUpload with no parts.

- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/TaggingResponsesV2IT.kt
- server/src/main/java/com/adobe/testing/s3mock/S3MockConfiguration.java
- server/src/main/java/com/adobe/testing/s3mock/TaggingHeaderConverter.java
- server/src/test/java/com/adobe/testing/s3mock/TaggingHeaderConverterTest.java
The default String -> List converters do not seem to work for the "&" delimiter.
Fixes #673
> Proper handling of "x-amz-tagging" header in PutObjectRequest.

- CHANGELOG.md
- README.md
- integration-tests/pom.xml
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/AmazonClientUploadIT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ErrorResponsesIT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ErrorResponsesV2IT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/S3TestBase.kt
- server/src/main/java/com/adobe/testing/s3mock/KmsValidationFilter.java
- server/src/main/java/com/adobe/testing/s3mock/store/KmsKeyStore.java
- server/src/test/java/com/adobe/testing/s3mock/store/KmsKeyStoreTest.java
This never worked according to AWS spec / docs.
Configuring the KMS keys must be done in ARN format, requests with SDK
or CLI are done with the KMS-key-ID only.
Fixes #702
> Proper handling of KMS keys.

- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/AmazonClientUploadV1IT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ErrorResponsesV1IT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ListObjectV1IT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/MultiPartUploadV1IT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/MultiPartUploadV2IT.kt
- server/pom.xml
- server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
- server/src/main/java/com/adobe/testing/s3mock/util/AwsHttpParameters.java
AWS SDK v1 apparently used the wrong path for ListMultiPartUploads requests (it was the only one adding a `/` to the end of the path), and they fixed that in v2?
Anyway, just adding the URI pattern did not work, had to debug other failing calls and tests because the S3 API often uses the same path and HTTP method for different calls, just adding or omitting parameters.
Most of our integration tests are using the V1 SDK only, so this problem did not surface until now.
#734
> Amazon SDK v2 does not work for ListMultiPartUploads

- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/BucketTestsV2IT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/PlainHttpIT.kt
- server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
- server/src/main/java/com/adobe/testing/s3mock/S3MockConfiguration.java
- server/src/main/resources/application-debug.properties
- server/src/test/java/com/adobe/testing/s3mock/FileStoreControllerTest.java
Using simplified bucket name validation.
When creating a bucket, check against simplified Regex whether the
bucket name is valid or not - only necessary for plain HTTP requests,
AWS SDKs (for Java) will validate the name before sending the request.
When calling other APIs, accept only valid bucket names in the path.
Also:
Log all request details when running in "debug" profile
N/A
> Let S3Mock only accept "valid" bucket names / debug info

- server/src/main/java/com/adobe/testing/s3mock/S3MockApplication.java
This annotation combines @Configuration and other annotations.
I am honestly not sure if this fixes the problem reported in #782, and which other customer projects may break with this change...
Fixes #782
> Use @SpringBootApplication to configure S3Mock

- CHANGELOG.md
- server/src/main/java/com/adobe/testing/s3mock/store/StoreConfiguration.java
Forgot that this is a feature - mount the root folder into Docker, so
that we can look at the created files while the S3Mock is running, or,
if `retainFilesOnExit` is set to true, even after S3Mock shuts down.
I'll have to think about how to integration test this later.
Fixes #786
> Correctly detect and use existing root folder

- CHANGELOG.md
- server/pom.xml
Adding a Spring Component Index file is a breaking change for all
clients of the s3mock.jar
Did not notice this when I added the index in 2.5.0
Fixes #782 #751
> Remove Spring Component Indexes

- CHANGELOG.md
- server/src/main/java/com/adobe/testing/s3mock/S3MockConfiguration.java
- server/src/main/java/com/adobe/testing/s3mock/S3MockProperties.java
- server/src/main/java/com/adobe/testing/s3mock/store/StoreConfiguration.java
- server/src/main/java/com/adobe/testing/s3mock/store/StoreProperties.java
If our "@Configuration" / "@ConfigurationProperties" classes are public,
customers can "@Import" them or use them in "@ContextConfiguration".
Fixes #751
> Allow customers to create ContextConfigurations.

- server/src/main/java/com/adobe/testing/s3mock/dto/CompleteMultipartUploadResult.java
- server/src/main/java/com/adobe/testing/s3mock/dto/CopyObjectResult.java
- server/src/main/java/com/adobe/testing/s3mock/dto/CopyPartResult.java
- server/src/main/java/com/adobe/testing/s3mock/dto/S3Object.java
- server/src/test/resources/com/adobe/testing/s3mock/dto/ListBucketResultTest_testSerialization.xml
- server/src/test/resources/com/adobe/testing/s3mock/dto/ListBucketResultV2Test_testSerialization.xml
Whenever S3Mock uses Serialization / Deserialization with Jackson, we must use our custom EtagSerializer / EtagDeserializer that wraps and unwraps the etag for the DTO.
Fixes #801
> ETags in requests and responses must comply to RFC-2616

- CHANGELOG.md
- integration-tests/pom.xml
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/CopyObjectV1IT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/CopyObjectV2IT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/S3TestBase.kt
- server/src/main/java/com/adobe/testing/s3mock/ObjectController.java
- server/src/main/java/com/adobe/testing/s3mock/store/ObjectStore.java
2.x is JDK8 LTS bytecode compatible, with Docker and JUnit / direct Java integration.
* Features and fixes
* LastModified must be updated when copying an object onto itself (fixes #811)
* Refactorings
* Split up integration tests by type
Fixes #811
> LastModified must be updated when copying an object onto itself.

- CHANGELOG.md
- build-config/pom.xml
- docker/pom.xml
- integration-tests/pom.xml
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/BucketV1IT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/BucketV2IT.kt
- pom.xml
- server/pom.xml
- server/src/main/java/com/adobe/testing/s3mock/S3MockConfiguration.java
- server/src/main/java/com/adobe/testing/s3mock/store/BucketStore.java
- server/src/main/java/com/adobe/testing/s3mock/store/ObjectStore.java
- server/src/main/java/com/adobe/testing/s3mock/store/StoreConfiguration.java
- server/src/test/java/com/adobe/testing/s3mock/store/BucketStoreTest.java
- server/src/test/java/com/adobe/testing/s3mock/store/MultipartStoreTest.java
- server/src/test/java/com/adobe/testing/s3mock/store/ObjectStoreTest.java
- server/src/test/java/com/adobe/testing/s3mock/store/StoreTestBase.java
- server/src/test/java/com/adobe/testing/s3mock/store/StoresWithExistingFileRootTest.java
- testsupport/common/pom.xml
- testsupport/junit4/pom.xml
- testsupport/junit5/pom.xml
- testsupport/pom.xml
- testsupport/testcontainers/pom.xml
- testsupport/testcontainers/src/main/java/com/adobe/testing/s3mock/testcontainers/S3MockContainer.java
- testsupport/testcontainers/src/test/java/com/adobe/testing/s3mock/testcontainers/S3MockContainerRestartOnRootfolderTest.java
- testsupport/testcontainers/src/test/java/com/adobe/testing/s3mock/testcontainers/S3MockContainerTestBase.java
- testsupport/testng/pom.xml
If the `root` configured for S3Mock contains files of a previous run (for instance because S3Mock is started with the `retainFilesOnExit` option), it should try and restore all in-memory data so that requests can be served using the existing files.
Fixes #818
> Support restarting S3Mock on existing root

- CHANGELOG.md
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/S3TestBase.kt
- testsupport/common/src/main/java/com/adobe/testing/s3mock/testsupport/common/S3MockStarter.java
- testsupport/testcontainers/src/test/java/com/adobe/testing/s3mock/testcontainers/S3MockContainerTestBase.java
This was the default in 2.17.x, changed in 2.18.x
S3Mock currently does not support subdomain style access to buckets.
Fixes #880
The real issue is #144, which is *not* fixed with this change.
> Let AWS SDKv2 use path style access

- CHANGELOG.md
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/GetPutDeleteObjectV2IT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/S3TestBase.kt
- server/src/main/java/com/adobe/testing/s3mock/store/BucketMetadata.java
UUIDs were the same for the same keys even in different buckets.
Fixes #877
> IDs in stores must be different for all objects

- CHANGELOG.md
- README.md
- build-config/pom.xml
- docker/Dockerfile
- docker/pom.xml
- integration-tests/pom.xml
- pom.xml
- server/pom.xml
- testsupport/common/pom.xml
- testsupport/junit4/pom.xml
- testsupport/junit5/pom.xml
- testsupport/pom.xml
- testsupport/testcontainers/pom.xml
- testsupport/testng/pom.xml
If needed, cpu and memory limits can be set for the container, the JVM will adjust automatically.
Fixes #922
> Let JVM use available Docker resources

- CHANGELOG.md
- server/src/main/java/com/adobe/testing/s3mock/S3Exception.java
- server/src/main/java/com/adobe/testing/s3mock/service/ObjectService.java
Previous implementation read the full stream into memory, leading to OutOfMemory errors if the file is larger than the available heap.
fixes #939
> Let S3Mock use streams for MD5 verification

- CHANGELOG.md
- integration-tests/pom.xml
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/BucketV1IT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/BucketV2IT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ListObjectV1IT.kt
- server/src/main/java/com/adobe/testing/s3mock/BucketController.java
- server/src/main/java/com/adobe/testing/s3mock/MultipartController.java
- server/src/main/java/com/adobe/testing/s3mock/ObjectController.java
- server/src/main/java/com/adobe/testing/s3mock/dto/ObjectKey.java
Match all bucket names in path pattern.
This makes it possible to return real S3 errors if buckets have invalid
names.
Fixes #935
> Return correct errors for invalid bucket names

- build-config/pom.xml
- docker/pom.xml
- integration-tests/pom.xml
- pom.xml
- server/pom.xml
- testsupport/common/pom.xml
- testsupport/junit4/pom.xml
- testsupport/junit5/pom.xml
- testsupport/pom.xml
- testsupport/testcontainers/pom.xml
- testsupport/testng/pom.xml
The "license-maven-plugin" configuration expects all changed files to have a copyright ending the year they are modified. A maven release updates all POMs, we need to update the copyright at the start of every year...
N/A
> Prepare releases in 2023

- CHANGELOG.md
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/CorsV2IT.kt
- server/src/main/java/com/adobe/testing/s3mock/BucketController.java
- server/src/main/java/com/adobe/testing/s3mock/MultipartController.java
- server/src/main/java/com/adobe/testing/s3mock/ObjectController.java
- server/src/test/java/com/adobe/testing/s3mock/ObjectControllerTest.java
This is a test application supposed to be used locally only. No reason to limit exposed response headers, since we want clients to receive the headers we add to responses.
Fixes #1023
> Expose all headers for CORS requests.

- .github/workflows/codeql-analysis.yml
- .github/workflows/maven-ci-and-prb.yml
- .github/workflows/maven-release.yml
Adopt is no longer maintained https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/
> ci: migrate to Temurin

- CHANGELOG.md
- build-config/pom.xml
- docker/pom.xml
- integration-tests/pom.xml
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/GetPutDeleteObjectV1IT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/GetPutDeleteObjectV2IT.kt
- pom.xml
- server/pom.xml
- server/src/main/java/com/adobe/testing/s3mock/MultipartController.java
- server/src/main/java/com/adobe/testing/s3mock/ObjectController.java
- server/src/main/java/com/adobe/testing/s3mock/service/MultipartService.java
- server/src/main/java/com/adobe/testing/s3mock/service/ObjectService.java
- server/src/main/java/com/adobe/testing/s3mock/store/MultipartStore.java
- server/src/main/java/com/adobe/testing/s3mock/store/MultipartUploadInfo.java
- server/src/main/java/com/adobe/testing/s3mock/store/ObjectStore.java
- server/src/main/java/com/adobe/testing/s3mock/store/S3ObjectMetadata.java
- server/src/main/java/com/adobe/testing/s3mock/util/HeaderUtil.java
- server/src/test/java/com/adobe/testing/s3mock/ObjectControllerTest.java
- server/src/test/java/com/adobe/testing/s3mock/store/MultipartStoreTest.java
- server/src/test/java/com/adobe/testing/s3mock/store/ObjectStoreTest.java
- server/src/test/java/com/adobe/testing/s3mock/store/StoreTestBase.java
- server/src/test/java/com/adobe/testing/s3mock/store/StoresWithExistingFileRootTest.java
- testsupport/common/pom.xml
- testsupport/junit4/pom.xml
- testsupport/junit5/pom.xml
- testsupport/pom.xml
- testsupport/testcontainers/pom.xml
- testsupport/testng/pom.xml
Store and return all encryption headers
Fixes #1178
> Store and return all encryption headers.

- CHANGELOG.md
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/PlainHttpIT.kt
- server/src/main/java/com/adobe/testing/s3mock/BucketController.java
- server/src/main/java/com/adobe/testing/s3mock/MultipartController.java
- server/src/main/java/com/adobe/testing/s3mock/ObjectController.java
GetObject had a wrong "produces" declarations, some others were not consistent. AWS SDK does not send "Accept" headers, but if we're using plain HTTP requests, a 406 NOT_ACCEPTABLE is returned from Spring MVC when a request comes in and the "Accept" / "Content-Type" headers do not match the expectations.
Fixes #1208
> Consistent consumes / produces declarations

- CHANGELOG.md
- server/src/main/java/com/adobe/testing/s3mock/store/BucketStore.java
- server/src/main/java/com/adobe/testing/s3mock/store/MultipartStore.java
- server/src/main/java/com/adobe/testing/s3mock/store/ObjectStore.java
- server/src/main/java/com/adobe/testing/s3mock/store/StoreConfiguration.java
* Always delete directories if retainFilesOnExit==false
* Do not exclude buckets called "test"
* Lock bucket when loading its objects
* Log # of objects loaded for each bucket.
Fixes #1224
> Fix startup on existing data folder issues

- README.md
Adding a link to the high-level diagrams including module, library dependency and others (https://sourcespy.com/github/adobes3mock/). Built directly from source and updated on schedule. Intended to simplify developer's introduction to the project.
In the spirit of transparency - I am the author of the diagrams. Hope contributors find it useful.
> Adding project map link to README.md

- CHANGELOG.md
- README.md
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ListObjectVersionsV2IT.kt
- server/src/main/java/com/adobe/testing/s3mock/BucketController.java
- server/src/main/java/com/adobe/testing/s3mock/dto/DeleteMarkerEntry.java
- server/src/main/java/com/adobe/testing/s3mock/dto/ListVersionsResult.java
- server/src/main/java/com/adobe/testing/s3mock/dto/ObjectVersion.java
- server/src/main/java/com/adobe/testing/s3mock/service/BucketService.java
- server/src/main/java/com/adobe/testing/s3mock/util/AwsHttpParameters.java
This version of the API currently DOES NOT LIST VERSIONS. This is just a dummy implementation that always returns a dummy version if the key exists in the bucket.
fixes #1215
> Add ListObjectVersions API

- .mvn/wrapper/maven-wrapper.properties
- CHANGELOG.md
- build-config/pom.xml
- docker/pom.xml
- integration-tests/pom.xml
- pom.xml
- server/pom.xml
- server/src/main/java/com/adobe/testing/s3mock/store/StoreConfiguration.java
- server/src/test/java/com/adobe/testing/s3mock/store/StoreConfigurationTest.java
- testsupport/common/pom.xml
- testsupport/junit4/pom.xml
- testsupport/junit5/pom.xml
- testsupport/pom.xml
- testsupport/testcontainers/pom.xml
- testsupport/testng/pom.xml
Let S3Mock load existing buckets and create initial buckets if they do not already exist.
#1433
> Support initial and existing buckets

- CHANGELOG.md
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/AclIT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/AwsChunkedEndcodingITV2.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/BucketV1IT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/BucketV2IT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ConcurrencyIT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/CopyObjectV1IT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/CopyObjectV2IT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/CorsV2IT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/CrtAsyncV2IT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/GetPutDeleteObjectV1IT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/GetPutDeleteObjectV2IT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/LegalHoldV2IT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ListObjectV1IT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ListObjectV1MaxKeysIT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ListObjectV1PaginationIT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ListObjectV2IT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ListObjectVersionsV2IT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/MultiPartUploadV1IT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/MultiPartUploadV2IT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ObjectTaggingV1IT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/PlainHttpIT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/PresignedUriV2IT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/RetentionV2IT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/S3TestBase.kt
- server/src/main/java/com/adobe/testing/s3mock/MultipartController.java
- server/src/main/java/com/adobe/testing/s3mock/ObjectController.java
- server/src/main/java/com/adobe/testing/s3mock/service/ObjectService.java
- server/src/main/java/com/adobe/testing/s3mock/util/HeaderUtil.java
This works for regular uploads and parts now.
UploadPart API now returns the checksum.
Fixes #1827
> Verify checksums on upload

- CHANGELOG.md
- build-config/pom.xml
- docker/pom.xml
- integration-tests/pom.xml
- pom.xml
- server/pom.xml
- server/src/main/java/com/adobe/testing/s3mock/BucketController.java
- server/src/main/java/com/adobe/testing/s3mock/ObjectController.java
- testsupport/common/pom.xml
- testsupport/junit4/pom.xml
- testsupport/junit5/pom.xml
- testsupport/pom.xml
- testsupport/testcontainers/pom.xml
- testsupport/testng/pom.xml
Some clients like the AWS CLI or curl do not necessarily use "application/xml" as the content-type when sending PUT requests to S3.
Fixes #1978
> Allow PUT requests without content-type application/xml

- CHANGELOG.md
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/CopyObjectV2IT.kt
- server/src/main/java/com/adobe/testing/s3mock/ObjectController.java
- server/src/main/java/com/adobe/testing/s3mock/service/ObjectService.java
- server/src/main/java/com/adobe/testing/s3mock/store/ObjectStore.java
- server/src/main/java/com/adobe/testing/s3mock/store/S3ObjectMetadata.java
- server/src/main/resources/application-trace.properties
- server/src/test/kotlin/com/adobe/testing/s3mock/store/ObjectStoreTest.kt
The headers we store as "storeHeaders" are part of the
"System-defined object metadata" which can be the only metadata
overwritten when copying objects.
See also https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html#SysMetadata
Fixes #2005
> Let CopyObject overwrite store headers

- README.md
Reverts adobe/S3Mock#1366
Sourcespy.com does not work any more.
> Revert "Adding project map link to README.md"

- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/PlainHttpIT.kt
- pom.xml
- server/pom.xml
- server/src/main/java/com/adobe/testing/s3mock/S3MockApplication.java
- server/src/main/java/com/adobe/testing/s3mock/S3MockConfiguration.java
- server/src/main/resources/application.properties
The AWS CRT-based S3 client does not work with Jetty 12.0.13+ (probably due to changed behaviour with 100-continue requests). With Tomcat, the CRT client works fine.
#2136
> Use Tomcat instead of Jetty

- CHANGELOG.md
- server/src/main/java/com/adobe/testing/s3mock/ObjectController.java
- server/src/main/java/com/adobe/testing/s3mock/service/ServiceBase.java
- server/src/main/java/com/adobe/testing/s3mock/store/BucketStore.java
- server/src/main/java/com/adobe/testing/s3mock/store/MultipartStore.java
- server/src/main/java/com/adobe/testing/s3mock/store/ObjectStore.java
- server/src/main/java/com/adobe/testing/s3mock/store/StoreBase.java
- server/src/main/java/com/adobe/testing/s3mock/store/StoreCleaner.java
- server/src/main/java/com/adobe/testing/s3mock/store/StoreConfiguration.java
- server/src/main/java/com/adobe/testing/s3mock/util/DigestUtil.java
- server/src/test/kotlin/com/adobe/testing/s3mock/ObjectControllerTest.kt
- server/src/test/kotlin/com/adobe/testing/s3mock/store/StoresWithExistingFileRootTest.kt
Refactor deletion at exit to use a `DisposableBean` instead of `File#deleteOnExit()`.
Also: close all InputStreams and OutputStreams.
#2143
> Refactor deletion of all files on exit

- build-config/pom.xml
- docker/pom.xml
- integration-tests/pom.xml
- pom.xml
- server/pom.xml
- testsupport/common/pom.xml
- testsupport/junit4/pom.xml
- testsupport/junit5/pom.xml
- testsupport/pom.xml
- testsupport/testcontainers/pom.xml
- testsupport/testng/pom.xml
The "license-maven-plugin" configuration expects all changed files to have a copyright ending the year they are modified. A maven release updates all POMs, we need to update the copyright at the start of every year...
N/A
> Prepare releases in 2025

- integration-tests/pom.xml
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/AclITV2.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/KotlinSDKIT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/S3TestBase.kt
- pom.xml
Use new Kotlin SDK for ITs
Use simplified Kotlin builder syntax in tests
N/A
> Add Kotlin SDK ITs, simplifications

- CHANGELOG.md
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/AwsChunkedEncodingIT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/S3TestBase.kt
- server/src/main/java/com/adobe/testing/s3mock/service/ServiceBase.java
- server/src/main/java/com/adobe/testing/s3mock/util/HeaderUtil.java
AWS docs specify that this encoding is not persisted or returned if it's the only value sent in the "Content-Encoding" header.
Fixes #2218
> Do not store "aws-chunked" encoding

- CHANGELOG.md
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/AclIT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/AwsChunkedEncodingIT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/GetPutDeleteObjectIT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ListObjectsIT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/MultiPartIT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/PlainHttpIT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/PresignedUrlIT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/S3TestBase.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/VersionsIT.kt
- pom.xml
- server/pom.xml
- server/src/main/java/com/adobe/testing/s3mock/S3Exception.java
- server/src/main/java/com/adobe/testing/s3mock/dto/Checksum.java
- server/src/main/java/com/adobe/testing/s3mock/dto/ChecksumAlgorithm.java
- server/src/main/java/com/adobe/testing/s3mock/service/ObjectService.java
- server/src/main/java/com/adobe/testing/s3mock/service/ServiceBase.java
- server/src/main/java/com/adobe/testing/s3mock/store/MultipartStore.java
- server/src/main/java/com/adobe/testing/s3mock/util/DigestUtil.java
- server/src/main/java/com/adobe/testing/s3mock/util/HeaderUtil.java
- server/src/test/kotlin/com/adobe/testing/s3mock/ChecksumTestUtil.kt
- server/src/test/kotlin/com/adobe/testing/s3mock/ObjectControllerTest.kt
- server/src/test/kotlin/com/adobe/testing/s3mock/service/ObjectServiceTest.kt
- server/src/test/kotlin/com/adobe/testing/s3mock/util/AwsChunkedDecodingChecksumInputStreamTest.kt
- server/src/test/kotlin/com/adobe/testing/s3mock/util/AwsUnsignedChunkedDecodingChecksumInputStreamTest.kt
- server/src/test/kotlin/com/adobe/testing/s3mock/util/DigestUtilTest.kt
Support crc64nvme checksum, add tests.
Refactor S3Mock and tests to use new checksum related types from AWS SDK v2.
#2334
> Support crc64nvme checksum

- CHANGELOG.md
- build-config/pom.xml
- docker/pom.xml
- integration-tests/pom.xml
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/AwsChunkedEncodingIT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ConcurrencyIT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/CopyObjectIT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/CrtAsyncIT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/GetPutDeleteObjectIT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/LegalHoldIT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ListObjectVersionsIT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ListObjectsIT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/MultipartIT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/PlainHttpIT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/PresignedUrlIT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/RetentionIT.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/S3TestBase.kt
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/VersionsIT.kt
- pom.xml
- server/pom.xml
- server/src/main/java/com/adobe/testing/s3mock/service/ObjectService.java
- testsupport/common/pom.xml
- testsupport/junit4/pom.xml
- testsupport/junit5/pom.xml
- testsupport/pom.xml
- testsupport/testcontainers/pom.xml
- testsupport/testng/pom.xml
S3 API accepts * for conditional requests on all APIs. All APIs but PutObject succeed with "*" as well.
Fixes #2371
> Let S3Mock accept * and "*" for conditional requests

- .mvn/wrapper/maven-wrapper.properties
- CHANGELOG.md
- mvnw
- mvnw.cmd
Update Maven to 3.9.9, Wrapper to 3.3.2
Ran `mvn wrapper:wrapper` to update all wrapper files.
N/A
> Update Maven to 3.9.9, Wrapper to 3.3.2

- docker/Dockerfile
Looks like this was finally fixed in a JRE 21 patch version
N/A
> Re-enable dependency based JRE

- server/src/main/java/com/adobe/testing/s3mock/S3MockApplication.java
> Fix legacy property overrrides.

- .junie/guidelines.md
- CHANGELOG.md
- docs/tasks.md
- integration-tests/pom.xml
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/MultipartIT.kt
- pom.xml
- server/src/main/java/com/adobe/testing/s3mock/MultipartController.java
- server/src/main/java/com/adobe/testing/s3mock/service/MultipartService.java
- server/src/main/java/com/adobe/testing/s3mock/store/MultipartStore.java
- server/src/main/java/com/adobe/testing/s3mock/store/StoreBase.java
- server/src/test/kotlin/com/adobe/testing/s3mock/MultipartControllerTest.kt
- server/src/test/kotlin/com/adobe/testing/s3mock/service/MultipartServiceTest.kt
- server/src/test/kotlin/com/adobe/testing/s3mock/store/MultipartStoreTest.kt
- testsupport/common/pom.xml
* Let Junie generate guidelines and tasks
* Junie: Optimize file storage for large objects
* Force dependency convergence to highest version
* The AWS Kotlin SDK depends on Kotlin 2.2.0 and newest Coroutines
dependencies. Maven manages versions down during convergence by default, leading to
runtime failures.
https://github.com/awslabs/aws-sdk-kotlin/issues/1654
> junie-evaluation

- .junie/guidelines.md
- CHANGELOG.md
- README.md
- docs/tasks.md
- integration-tests/pom.xml
- pom.xml
- server/pom.xml
- server/src/main/java/com/adobe/testing/s3mock/MultipartController.java
- server/src/main/java/com/adobe/testing/s3mock/dto/RegionSerializer.java
- server/src/test/kotlin/com/adobe/testing/s3mock/BaseControllerTest.kt
- server/src/test/kotlin/com/adobe/testing/s3mock/BucketControllerTest.kt
- server/src/test/kotlin/com/adobe/testing/s3mock/ContextPathObjectStoreControllerTest.kt
- server/src/test/kotlin/com/adobe/testing/s3mock/FaviconControllerTest.kt
- server/src/test/kotlin/com/adobe/testing/s3mock/MultipartControllerTest.kt
- server/src/test/kotlin/com/adobe/testing/s3mock/ObjectControllerTest.kt
- server/src/test/kotlin/com/adobe/testing/s3mock/dto/LocationConstraintTest.kt
- server/src/test/kotlin/com/adobe/testing/s3mock/service/BucketServiceTest.kt
- server/src/test/kotlin/com/adobe/testing/s3mock/service/MultipartServiceTest.kt
- server/src/test/kotlin/com/adobe/testing/s3mock/service/ObjectServiceTest.kt
- server/src/test/kotlin/com/adobe/testing/s3mock/service/ServiceTestBase.kt
- server/src/test/kotlin/com/adobe/testing/s3mock/store/BucketStoreTest.kt
- server/src/test/kotlin/com/adobe/testing/s3mock/store/KmsKeyStoreTest.kt
- server/src/test/kotlin/com/adobe/testing/s3mock/store/MultipartStoreTest.kt
- server/src/test/kotlin/com/adobe/testing/s3mock/store/ObjectStoreTest.kt
- server/src/test/kotlin/com/adobe/testing/s3mock/store/StoresWithExistingFileRootTest.kt
- server/src/test/resources/com/adobe/testing/s3mock/dto/LocationConstraintTest_testSerialization_usEastOne.xml
> Junie tasks ctd

- CHANGELOG.md
- build-config/pom.xml
- docker/pom.xml
- integration-tests/pom.xml
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/MultipartIT.kt
- pom.xml
- server/pom.xml
- server/src/main/java/com/adobe/testing/s3mock/MultipartController.java
- server/src/main/java/com/adobe/testing/s3mock/service/MultipartService.java
- server/src/main/java/com/adobe/testing/s3mock/store/MultipartStore.java
- server/src/main/java/com/adobe/testing/s3mock/store/MultipartUploadInfo.java
- server/src/test/kotlin/com/adobe/testing/s3mock/MultipartControllerTest.kt
- server/src/test/kotlin/com/adobe/testing/s3mock/dto/CompleteMultipartUploadResultTest.kt
- server/src/test/kotlin/com/adobe/testing/s3mock/service/MultipartServiceTest.kt
- testsupport/common/pom.xml
- testsupport/junit4/pom.xml
- testsupport/junit5/pom.xml
- testsupport/pom.xml
- testsupport/testcontainers/pom.xml
- testsupport/testng/pom.xml
CompleteMultipartUpload will not delete MultipartUpload data, only the parts.
This is only part of a fix, we really shouldn't delete parts at all and preserve all multipart data, streaming a full binary on getObject requests.
#2586
> CompleteMultipartUpload is idempotent

- .github/workflows/maven-ci-and-prb.yml
- CHANGELOG.md
- README.md
- docker/pom.xml
- integration-tests/pom.xml
- integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/VersionsIT.kt
- pom.xml
- server/pom.xml
- server/src/main/java/com/adobe/testing/s3mock/BucketController.java
- testsupport/common/pom.xml
- testsupport/junit4/pom.xml
- testsupport/junit5/pom.xml
- testsupport/pom.xml
- testsupport/testcontainers/pom.xml
- testsupport/testng/pom.xml
> Prepare for 4.9.0
